environment:
  matrix:
    - target: nightly-x86_64-pc-windows-msvc

install:
  # Download the Rust and Cargo installer.
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:target}.msi"

  # Install Rust and Cargo and wait for installation to finish by using Write-Output.
  - ps: msiexec /package "rust-${env:target}.msi" /quiet /norestart | Write-Output

  # Pick up the new Path variable after the installer modified it.
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")

  # Print versions for future reference.
  - rustc --version
  - cargo --version

build_script:
  - cargo build

test_script:
  - cargo test
